/* 
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * OpenAPI spec version: 3.0.15
 * Contact: api@oanda.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.IO;

namespace QuantConnect.OandaBrokerage.RestV20.Model
{
    public struct FileParameter
    {
        /// <summary>
        /// The name of the parameter
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The content stream.
        /// </summary>
        public Stream Writer { get; set; }

        /// <summary>
        /// The name of the file.
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// The content type
        /// </summary>
        public string ContentType { get; set; }

        /// <summary>
        /// The content length.
        /// </summary>
        public long ContentLength { get; set; }

        /// <summary>
        /// Helper to create a FileParameter from a byte array.
        /// </summary>
        public static FileParameter Create(string name, byte[] data, string filename, string contentType = "application/octet-stream")
        {
            var stream = new MemoryStream(data);
            return new FileParameter
            {
                Name = name,
                Writer = stream,
                FileName = filename,
                ContentType = contentType,
                ContentLength = data.Length
            };
        }

        /// <summary>
        /// Helper to create a FileParameter from a stream.
        /// </summary>
        public static FileParameter Create(string name, Stream stream, string filename, string contentType = "application/octet-stream")
        {
            return new FileParameter
            {
                Name = name,
                Writer = stream,
                FileName = filename,
                ContentType = contentType,
                ContentLength = stream.Length
            };
        }
    }
}